# Generated by Django 3.2.7 on 2021-10-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='num',
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
