# Generated by Django 3.2.7 on 2021-11-01 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='exist',
            field=models.BooleanField(default=True),
        ),
    ]
