# Generated by Django 3.2.7 on 2021-11-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments_model',
            name='comment',
            field=models.TextField(max_length=150),
        ),
    ]
