# Generated by Django 3.2.7 on 2021-11-02 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comments_model_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments_model',
            name='is_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments_model',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rcomment', to='comments.comments_model'),
        ),
    ]
